### ISSUE TITLE
Integration into Rock-ROS bridge release docker container

### ISSUE THREAD

**Issue by bkocev** [rock-control/control-orogen-auv_control#37]
Hi everyone,

I am trying to integrate this orogen component in the Rock-ROS bridge.
Unfortunately, I am getting a build error using amake. Belo w is the traceback.

Traceback (most recent call last):
      File "/opt/ros/melodic/lib/python2.7/dist-packages/geneus/geneus_main.py", line 137, in genmain
        pkg_map = get_pkg_map()
      File "/opt/ros/melodic/lib/python2.7/dist-packages/geneus/geneus_main.py", line 56, in get_pkg_map
        pkgs = packages.find_packages(ws)
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 89, in find_packages
        packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 150, in find_packages_allowing_duplicates
        xml, filename=filename, warnings=warnings)
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 542, in parse_package_string
        raise InvalidPackage('The manifest contains invalid XML:\n%s' % ex, filename)
    InvalidPackage: Error(s) in package '/opt/rock_workspace/install/lib/x86_64-linux-gnu/ruby/2.5.0/orogen/templates/typekit/package.xml':
    The manifest contains invalid XML:
    not well-formed (invalid token): line 2, column 9
    ERROR:  Error(s) in package '/opt/rock_workspace/install/lib/x86_64-linux-gnu/ruby/2.5.0/orogen/templates/typekit/package.xml':
    The manifest contains invalid XML:
    not well-formed (invalid token): line 2, column 9
    .orogen/typekit/transports/ros/CMakeFiles/orogen_auv_control_msgs_generate_messages_eus.dir/build.make:134: recipe for target 'devel/share/roseus/ros/orogen_auv_control_msgs/manifest.l' failed
    make[2]: *** [devel/share/roseus/ros/orogen_auv_control_msgs/manifest.l] Error 3
    CMakeFiles/Makefile2:1133: recipe for target '.orogen/typekit/transports/ros/CMakeFiles/orogen_auv_control_msgs_generate_messages_eus.dir/all' failed
    make[1]: *** [.orogen/typekit/transports/ros/CMakeFiles/orogen_auv_control_msgs_generate_messages_eus.dir/all] Error 2

I am guessing there might be an issue with the python version in the rock-ros bridge docker container out of which I got a release version. Nevertheless, I tried to update/upgrade as much as possible. Currently, I set python using autoproj reconfigure to /usr/bin/python2.7 but still it does not work.

Any remarks/suggestions would be very welcome.

Thanks,
Bojan Kocev.

**Comment by bkocev** [comment]
I found a, I guess temporary, solution. I had to modify the following file  install/lib/x86_64-linux-gnu/ruby/2.5.0/orogen/templates/typekit/package.xml. Now it look as follows:
```xml
<package>
 <!-- <name><%=typekit.name %>-typekit</name> -->
 <name> typekit </name>
 <version>0.0.1</version>
 <description>
 <!-- <%= typekit.name %>-typekit description -->
 </description>
 <!--NOTE: set the license and author before you publish this code-->
 <license>LGPLv2+</license>
 <author>Unknown Author</author>
 <maintainer email="unknown@maintainer.com">Unknown Author</maintainer>
 
 <buildtool_depend>cmake</buildtool_depend>
 
 <build_depend>rtt</build_depend>
 <build_depend>rtt_typelib</build_depend>
 <run_depend>rtt</run_depend>
 <run_depend>rtt_typelib</run_depend>
 
 <export>
 <build_type>
 cmake
 </build_type>
 </export>
</package>
```

In principle, I had to comment lines 2 and 5 (now line 6) and include line 3. No clue why I had to modify this file ... not sure if someone modified it and included the modification in the Docker release image.

**Comment by bkocev** [comment]
It took a few edits until I figured out how to paste xml on github. :)

**Comment by doudou** [comment]
Looks like something (you ?) is running catkin within the Rock workspace.... This should definitely not happen.

**Comment by bkocev** [comment]
Maybe, because it is a Rock-ROS bridge? :)
